#!/usr/bin/env python3
"""
Generate curriculum for Grades 7-9 with illustrations
Target: ~80 sets per grade to match distribution
Uses Claude API for content generation
"""

import os
import json
import time
import base64
from datetime import datetime
from pathlib import Path
from anthropic import Anthropic

# Configuration
CLAUDE_API_KEY = os.getenv('CLAUDE_API_KEY')
if not CLAUDE_API_KEY:
    print("❌ Error: CLAUDE_API_KEY not found")
    print("Make sure .env file is loaded")
    exit(1)

client = Anthropic(api_key=CLAUDE_API_KEY)

# Paths
PROJECT_ROOT = Path(__file__).parent.parent
CURRICULUM_FILE = PROJECT_ROOT / 'src' / 'data' / 'curriculum.json'
LOG_FILE = PROJECT_ROOT / 'generation_7_9.log'
IMAGES_DIR = PROJECT_ROOT / 'public' / 'curriculum-images'

# Ensure images directory exists
IMAGES_DIR.mkdir(parents=True, exist_ok=True)

def log(message):
    """Log to console and file"""
    timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    log_message = f"[{timestamp}] {message}"
    print(log_message)
    with open(LOG_FILE, 'a') as f:
        f.write(log_message + '\n')

def generate_curriculum_set(grade, topic, subtopic, set_number):
    """Generate a curriculum set using Claude with illustration support"""
    try:
        # Determine which questions need illustrations
        illustration_guidance = ""
        if topic in ['Geometry', 'Graphing', 'Coordinate Plane', 'Functions']:
            illustration_guidance = """
For geometric or graphing questions, include an "illustration" field with a detailed description 
of what should be drawn. Format: "illustration": "Description of diagram/graph to generate"
Example: "illustration": "Graph showing y = 2x + 3 on coordinate plane from -5 to 5"
"""
        
        prompt = f"""Generate a math curriculum set for Grade {grade}.

Topic: {topic}
Subtopic: {subtopic}

Create 8-10 multiple choice questions appropriate for Grade {grade}.
Each question should have 4 options.
{illustration_guidance}

Return ONLY valid JSON (no markdown) in this exact format:
{{
  "id": "{grade}-{topic.lower().replace(' ', '-')}-{subtopic.lower().replace(' ', '-')}-{set_number}",
  "title": "{subtopic} - Set {set_number}",
  "description": "Practice {subtopic.lower()} for Grade {grade}",
  "grade_level": {grade},
  "topic": "{topic}",
  "questions": [
    {{
      "question": "Question text",
      "options": ["Option A", "Option B", "Option C", "Option D"],
      "answer": "Option A",
      "explanation": "Why this is correct",
      "illustration": "Optional: Description of diagram if needed"
    }}
  ]
}}

Make questions progressively harder within the set. Use real-world contexts.
For algebra questions, show work steps in explanations.
For geometry, include diagrams where helpful."""

        message = client.messages.create(
            model="claude-3-haiku-20240307",  # Using Haiku (available with this API key)
            max_tokens=4096,
            messages=[{"role": "user", "content": prompt}]
        )
        
        response_text = message.content[0].text.strip()
        
        # Clean markdown if present
        if response_text.startswith('```json'):
            response_text = response_text.split('```json')[1].split('```')[0].strip()
        elif response_text.startswith('```'):
            response_text = response_text.split('```')[1].split('```')[0].strip()
        
        curriculum_set = json.loads(response_text)
        curriculum_set['grade_level'] = grade  # Ensure correct grade
        
        # Process illustrations - convert descriptions to placeholder paths
        # In production, these would be generated by an image generation service
        for i, question in enumerate(curriculum_set.get('questions', [])):
            if 'illustration' in question and question['illustration']:
                # Create a filename based on the set and question
                img_filename = f"grade{grade}-{topic.lower().replace(' ', '-')}-set{set_number}-q{i+1}.png"
                question['image'] = f"/curriculum-images/{img_filename}"
                # Keep illustration description for future generation
                question['illustration_description'] = question.pop('illustration')
        
        return curriculum_set
        
    except Exception as e:
        log(f"❌ Error: {e}")
        return None

# Topics for Grades 7-9
topics = [
    # Grade 7 - Target ~80 sets
    {'grade': 7, 'topic': 'Pre-Algebra', 'subtopics': ['Integers', 'Order of Operations', 'Expressions', 'Equations', 'Inequalities']},
    {'grade': 7, 'topic': 'Ratios and Proportions', 'subtopics': ['Ratios', 'Rates', 'Proportions', 'Scale Drawings', 'Percent']},
    {'grade': 7, 'topic': 'Geometry', 'subtopics': ['Angles', 'Triangles', 'Quadrilaterals', 'Circles', 'Area and Perimeter']},
    {'grade': 7, 'topic': 'Statistics', 'subtopics': ['Mean and Median', 'Data Analysis', 'Probability']},
    
    # Grade 8 - Target ~80 sets
    {'grade': 8, 'topic': 'Algebra', 'subtopics': ['Linear Equations', 'Systems of Equations', 'Functions', 'Slope', 'Graphing']},
    {'grade': 8, 'topic': 'Geometry', 'subtopics': ['Pythagorean Theorem', 'Volume', 'Surface Area', 'Transformations', 'Congruence']},
    {'grade': 8, 'topic': 'Exponents', 'subtopics': ['Powers', 'Scientific Notation', 'Square Roots', 'Cube Roots']},
    {'grade': 8, 'topic': 'Statistics', 'subtopics': ['Scatter Plots', 'Linear Models', 'Two-Way Tables']},
    
    # Grade 9 - Target ~80 sets
    {'grade': 9, 'topic': 'Algebra I', 'subtopics': ['Polynomials', 'Factoring', 'Quadratic Equations', 'Quadratic Functions', 'Exponential Functions']},
    {'grade': 9, 'topic': 'Geometry', 'subtopics': ['Coordinate Geometry', 'Parallel Lines', 'Triangle Properties', 'Similarity', 'Right Triangles']},
    {'grade': 9, 'topic': 'Functions', 'subtopics': ['Function Notation', 'Domain and Range', 'Transformations', 'Inverse Functions']},
    {'grade': 9, 'topic': 'Statistics', 'subtopics': ['Data Distributions', 'Standard Deviation', 'Regression']},
]

def main():
    """Generate content for Grades 7-9"""
    log("=" * 60)
    log("🚀 Generating Curriculum for Grades 7-9")
    log("=" * 60)
    
    # Load existing
    if CURRICULUM_FILE.exists():
        with open(CURRICULUM_FILE, 'r') as f:
            curriculum = json.load(f)
    else:
        curriculum = []
    
    log(f"📚 Loaded {len(curriculum)} existing sets")
    
    # Count by grade
    grade_counts = {}
    for item in curriculum:
        grade = item.get('grade_level', 0)
        grade_counts[grade] = grade_counts.get(grade, 0) + 1
    
    log("Current distribution:")
    for grade in sorted(grade_counts.keys()):
        log(f"  Grade {grade}: {grade_counts[grade]} sets")
    
    # Generate new content
    sets_per_subtopic = 4  # 4 sets per subtopic
    total_generated = 0
    
    for topic_data in topics:
        grade = topic_data['grade']
        topic = topic_data['topic']
        subtopics = topic_data['subtopics']
        
        for subtopic in subtopics:
            for set_num in range(1, sets_per_subtopic + 1):
                log(f"📝 Grade {grade} - {topic} - {subtopic} - Set {set_num}")
                
                curriculum_set = generate_curriculum_set(grade, topic, subtopic, set_num)
                
                if curriculum_set:
                    curriculum.append(curriculum_set)
                    total_generated += 1
                    
                    # Save every 10 sets
                    if total_generated % 10 == 0:
                        with open(CURRICULUM_FILE, 'w') as f:
                            json.dump(curriculum, f, indent=2)
                        log(f"✅ Saved {len(curriculum)} total sets ({total_generated} new)")
                
                # Rate limiting (Claude can handle 0.5s)
                time.sleep(0.5)
    
    # Final save
    with open(CURRICULUM_FILE, 'w') as f:
        json.dump(curriculum, f, indent=2)
    
    log("=" * 60)
    log(f"✅ COMPLETE! Generated {total_generated} new sets")
    log(f"📊 Total curriculum sets: {len(curriculum)}")
    log("=" * 60)
    
    # Show new distribution
    grade_counts = {}
    for item in curriculum:
        grade = item.get('grade_level', 0)
        grade_counts[grade] = grade_counts.get(grade, 0) + 1
    
    log("\nNew distribution:")
    for grade in sorted(grade_counts.keys()):
        log(f"  Grade {grade}: {grade_counts[grade]} sets")

if __name__ == '__main__':
    main()
